apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-order-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-order
  template:
    metadata:
      labels:
        app: ticketing-order
    spec:
      containers:
        - name: ticketing-order
          image: bungdanar/ticketing-order
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://ticketing-order-mongo-srv:27017/order'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-order-srv
spec:
  selector:
    app: ticketing-order
  ports:
    - name: ticketing-order
      protocol: TCP
      port: 3000
      targetPort: 3000
